name: NodeJS with Webpack

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
 runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cypress tests
        uses: ./
        with:
          working-directory: cypress
          build: npx cypress info

    - name: Build
      run: |
        npm install
        npx webpack
        npx cypress run    
